/*
 * Veritas Information Classifier (VIC)
 * APIs
 *
 * OpenAPI spec version: Resource Specific
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AllowedValue;
import java.util.ArrayList;
import java.util.List;

/**
 * MetadataDefinition
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-12T23:02:37.653Z")
public class MetadataDefinition {
  @SerializedName("name")
  private String name = null;

  @SerializedName("displayName")
  private String displayName = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    @SerializedName("String")
    STRING("String"),
    
    @SerializedName("Number")
    NUMBER("Number"),
    
    @SerializedName("DateTime")
    DATETIME("DateTime");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("allowedValues")
  private List<AllowedValue> allowedValues = new ArrayList<AllowedValue>();

  @SerializedName("aliases")
  private List<String> aliases = new ArrayList<String>();

  public MetadataDefinition name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MetadataDefinition displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public MetadataDefinition type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public MetadataDefinition allowedValues(List<AllowedValue> allowedValues) {
    this.allowedValues = allowedValues;
    return this;
  }

  public MetadataDefinition addAllowedValuesItem(AllowedValue allowedValuesItem) {
    this.allowedValues.add(allowedValuesItem);
    return this;
  }

   /**
   * Get allowedValues
   * @return allowedValues
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AllowedValue> getAllowedValues() {
    return allowedValues;
  }

  public void setAllowedValues(List<AllowedValue> allowedValues) {
    this.allowedValues = allowedValues;
  }

  public MetadataDefinition aliases(List<String> aliases) {
    this.aliases = aliases;
    return this;
  }

  public MetadataDefinition addAliasesItem(String aliasesItem) {
    this.aliases.add(aliasesItem);
    return this;
  }

   /**
   * Get aliases
   * @return aliases
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getAliases() {
    return aliases;
  }

  public void setAliases(List<String> aliases) {
    this.aliases = aliases;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetadataDefinition metadataDefinition = (MetadataDefinition) o;
    return Objects.equals(this.name, metadataDefinition.name) &&
        Objects.equals(this.displayName, metadataDefinition.displayName) &&
        Objects.equals(this.type, metadataDefinition.type) &&
        Objects.equals(this.allowedValues, metadataDefinition.allowedValues) &&
        Objects.equals(this.aliases, metadataDefinition.aliases);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, displayName, type, allowedValues, aliases);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetadataDefinition {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    allowedValues: ").append(toIndentedString(allowedValues)).append("\n");
    sb.append("    aliases: ").append(toIndentedString(aliases)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

