/*
 * Veritas Information Classifier (VIC)
 * APIs
 *
 * OpenAPI spec version: Resource Specific
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Node
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-12T23:02:37.653Z")

public class Node {
  /**
   * Determines whether this node is a condition node or an operator node. NOTE: If ConditionNode & OperatorNode are not visible in the Swagger UI, please consult the Swagger json for details.
   */
  public enum TypeEnum {
    @SerializedName("condition")
    CONDITION("condition"),
    
    @SerializedName("operator")
    OPERATOR("operator");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  public Node type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Determines whether this node is a condition node or an operator node. NOTE: If ConditionNode & OperatorNode are not visible in the Swagger UI, please consult the Swagger json for details.
   * @return type
  **/
  @ApiModelProperty(example = "null", required = true, value = "Determines whether this node is a condition node or an operator node. NOTE: If ConditionNode & OperatorNode are not visible in the Swagger UI, please consult the Swagger json for details.")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Node node = (Node) o;
    return Objects.equals(this.type, node.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Node {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

