/*
 * Veritas Information Classifier (VIC)
 * APIs
 *
 * OpenAPI spec version: Resource Specific
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Link;
import io.swagger.client.model.PolicyBody;
import java.util.ArrayList;
import java.util.List;

/**
 * Policy
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-12T23:02:37.653Z")
public class Policy {
  @SerializedName("links")
  private List<Link> links = new ArrayList<Link>();

  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("enabled")
  private Boolean enabled = null;

  @SerializedName("categories")
  private List<String> categories = new ArrayList<String>();

  @SerializedName("tags")
  private List<String> tags = new ArrayList<String>();

  @SerializedName("body")
  private PolicyBody body = null;

  @SerializedName("engineBody")
  private String engineBody = null;

  @SerializedName("custom")
  private Boolean custom = null;

  public Policy links(List<Link> links) {
    this.links = links;
    return this;
  }

  public Policy addLinksItem(Link linksItem) {
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public Policy id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Policy name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Display name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Display name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Policy description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Policy enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * If true, the policy is active for the tenant and will be used for document classification.
   * @return enabled
  **/
  @ApiModelProperty(example = "null", value = "If true, the policy is active for the tenant and will be used for document classification.")
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public Policy categories(List<String> categories) {
    this.categories = categories;
    return this;
  }

  public Policy addCategoriesItem(String categoriesItem) {
    this.categories.add(categoriesItem);
    return this;
  }

   /**
   * A list of categories that the policy falls into.  Categories may be hierarchical, e.g. industry/medical
   * @return categories
  **/
  @ApiModelProperty(example = "&quot;[industry/medical, us/medical]&quot;", value = "A list of categories that the policy falls into.  Categories may be hierarchical, e.g. industry/medical")
  public List<String> getCategories() {
    return categories;
  }

  public void setCategories(List<String> categories) {
    this.categories = categories;
  }

  public Policy tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public Policy addTagsItem(String tagsItem) {
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * The tags returned from a classification operation when the policy matches a document.
   * @return tags
  **/
  @ApiModelProperty(example = "null", value = "The tags returned from a classification operation when the policy matches a document.")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public Policy body(PolicyBody body) {
    this.body = body;
    return this;
  }

   /**
   * Policy body that defines how rules are used to enforce the policy.
   * @return body
  **/
  @ApiModelProperty(example = "null", value = "Policy body that defines how rules are used to enforce the policy.")
  public PolicyBody getBody() {
    return body;
  }

  public void setBody(PolicyBody body) {
    this.body = body;
  }

  public Policy engineBody(String engineBody) {
    this.engineBody = engineBody;
    return this;
  }

   /**
   * Policy body in its raw engine-specific form. May be empty for custom policies.
   * @return engineBody
  **/
  @ApiModelProperty(example = "null", value = "Policy body in its raw engine-specific form. May be empty for custom policies.")
  public String getEngineBody() {
    return engineBody;
  }

  public void setEngineBody(String engineBody) {
    this.engineBody = engineBody;
  }

  public Policy custom(Boolean custom) {
    this.custom = custom;
    return this;
  }

   /**
   * If true the policy is a custom policy defined by a user.  If false, the policy is a standard built-in policy.
   * @return custom
  **/
  @ApiModelProperty(example = "null", value = "If true the policy is a custom policy defined by a user.  If false, the policy is a standard built-in policy.")
  public Boolean getCustom() {
    return custom;
  }

  public void setCustom(Boolean custom) {
    this.custom = custom;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Policy policy = (Policy) o;
    return Objects.equals(this.links, policy.links) &&
        Objects.equals(this.id, policy.id) &&
        Objects.equals(this.name, policy.name) &&
        Objects.equals(this.description, policy.description) &&
        Objects.equals(this.enabled, policy.enabled) &&
        Objects.equals(this.categories, policy.categories) &&
        Objects.equals(this.tags, policy.tags) &&
        Objects.equals(this.body, policy.body) &&
        Objects.equals(this.engineBody, policy.engineBody) &&
        Objects.equals(this.custom, policy.custom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, id, name, description, enabled, categories, tags, body, engineBody, custom);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Policy {\n");
    
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    engineBody: ").append(toIndentedString(engineBody)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

